### ISSUE TITLE
what is the std package?

### ISSUE THREAD

**Issue by vandenman** [jasp-stats/jaspMixedModels#13]
@FBartos @TimKDJ I've removed the package `std` from the description in https://github.com/jasp-stats/jaspMixedModels/commit/f62d82e0bf3602c78111e38dca22fca1300974c7 because it's not available on CRAN. I also couldn't find any references to it in the code. If it's required, please add a remote to the DESCRIPTION file.

**Comment by TimKDJ** [comment]
Yeah that was misparsed in `if (any(attr(model, "class") %in% c("std::runtime_error", "C++Error", "error"))) {`
